# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Joker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Joker
  pod "Google-Mobile-Ads-SDK"
  pod 'SnapKit', '~> 5.0.0'
  pod 'ZLSwipeableViewSwift'
	pod 'UIColor+FlatColors'
	pod 'Cartography'

end
